server:
  port: 8080

spring:
  application:
    name: myapp-back
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: test
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 50
      initialization-fail-timeout: 0

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
            batch_size: 5000
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#ibm:
#  mq:
#    queue-manager: QM1
#    channel: DEV.APP.SVRCONN
#    client-id: myapp-client
#    user: admin
#    password: passw0rd
#    host: localhost
#    port: 1414
